#!/bin/sh
set -x

#Bring down bridges and delete
ifconfig ovsbr1 down
ifconfig ovsbr2 down
ifconfig ovsbr3 down
ifconfig ovsbr4 down
brctl delbr ovsbr1
brctl delbr ovsbr2
brctl delbr ovsbr3
brctl delbr ovsbr4

#Delete TAP devices
tunctl -d ovs_tap1
tunctl -d ovs_tap2
tunctl -d ovs_tap3
tunctl -d ovs_tap4
tunctl -d debA_tap1
tunctl -d debB_tap1
tunctl -d debC_tap1
tunctl -d debD_tap1